# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :snapshot do
    # add actions here: https://docs.fastlane.tools/actions
    pod_push(path: "ProbeSwiftCommon.podspec", repo: "ProbePrivate")
  end
end
